# This file tells Render how to deploy your service
# Place this in your repository root (not ml_service folder)

services:
  - type: web
    name: yinizai-ml-service
    env: docker
    region: oregon # Choose: oregon, frankfurt, singapore
    plan: starter # Free tier: free, Paid: starter ($7/mo)
    branch: main
    healthCheckPath: /health
    autoDeploy: true

    # Environment variables (set these in Render dashboard with actual values)
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: MIN_TRAINING_SAMPLES
        value: 10
      # Add these in Render dashboard:
      # - key: DB_HOST
      #   value: your-aiven-mysql-host
      # - key: DB_USER  
      #   value: avnadmin
      # - key: DB_PASSWORD
      #   value: your-aiven-password
      # - key: DB_NAME
      #   value: defaultdb
      # - key: SECRET_KEY
      #   value: your-secret-key
