# This file tells Render how to deploy your service
# Optimized for FREE TIER (512MB RAM limit)

services:
  - type: web
    name: yinizai-ml-service
    env: docker
    region: oregon # Choose: oregon, frankfurt, singapore
    plan: free # FREE TIER - 512MB RAM limit
    branch: main
    healthCheckPath: /health
    autoDeploy: true

    # Environment variables optimized for free tier
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: warning  # Reduce logging to save memory
      - key: MIN_TRAINING_SAMPLES
        value: 5  # Reduce sample size for free tier
      - key: WORKERS
        value: 1  # Single worker to save memory
      - key: MAX_REQUESTS
        value: 50  # Limit requests per worker
      # Add these in Render dashboard:
      # - key: DB_HOST
      #   value: your-aiven-mysql-host
      # - key: DB_USER  
      #   value: avnadmin
      # - key: DB_PASSWORD
      #   value: your-aiven-password
      # - key: DB_NAME
      #   value: defaultdb
      # - key: SECRET_KEY
      #   value: your-secret-key
